
trigger: none

pool:
  default

stages:
  - stage: CI
    jobs:
      - job: Terraforminit
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Newconnection'
              backendAzureRmOverrideSubscriptionID: 'f9fb190e-2a79-4b5f-b614-0f469a025fb0'
              backendAzureRmResourceGroupName: 'gonu'
              backendAzureRmStorageAccountName: 'gonustore'
              backendAzureRmContainerName: 'gonustorecontainer'
              backendAzureRmKey: 'develpment.terraform.tfstate'
